# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabreta Ltd
email: info@gabreta.ltd
description: > # this means to ignore newlines until "baseurl:"
  Digital Accessibility & Software Engineering Consultancy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabretaltd.github.io" # the base hostname & protocol for your site
#twitter_username: BorisDusek
github_username:  gabretaltd
# Build settings
markdown: kramdown

theme: jekyll-theme-cayman